name: Build and release proxmox-truenas from separate source repo

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  GITHUB_TAG: 'latest'
  TARGET_NAME: 'proxmox-truenas'
  TARGET_REPO: 'boomshankerx/proxmox-truenas'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout packaging repo (this repo)
        uses: actions/checkout@v4

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ secrets.RELEASE_TOKEN }}
          path: source
          fetch-depth: 0

      - name: Install dpkg
        run: sudo apt-get update && sudo apt-get install -y dpkg

      - name: Compute full version from source repo
        id: version
        run: |
          cd source
          BASE_VERSION=$(cat VERSION)
          COMMIT_COUNT=$(git rev-list --count HEAD)
          FULL_VERSION="${BASE_VERSION}.${COMMIT_COUNT}"
          echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
          echo "Computed version: $FULL_VERSION"
          cd ..

      - name: Fix script permissions
        run: |
          chmod 0755 stable/DEBIAN/postinst || true
          chmod 0755 stable/DEBIAN/postrm || true

      - name: Update DEBIAN/control with version
        run: |
          sed -i "s/^Version:.*/Version: ${FULL_VERSION}/" stable/DEBIAN/control

      - name: Build .deb package
        run: |
          mkdir -p dist
          dpkg-deb -Zgzip --build stable dist/${TARGET_NAME}_${FULL_VERSION}_all.deb

      - name: Move 'latest' tag in proxmox-truenas repo
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git
          cd ${TARGET_NAME}
          git fetch origin main
          git tag -f ${GITHUB_TAG} origin/main
          git push -f origin ${GITHUB_TAG}

      - name: Delete existing release for 'latest' (if any)
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          gh release delete ${GITHUB_TAG} \
            --repo ${TARGET_REPO} \
            --yes

      - name: Recreate 'latest' release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          gh release create ${GITHUB_TAG} \
            --repo ${TARGET_REPO} \
            --title "Latest Release: ${FULL_VERSION}" \
            --notes "Auto-updated from main at version ${FULL_VERSION}" \

      - name: Upload .deb to release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          gh release upload ${GITHUB_TAG} \
            dist/${TARGET_NAME}_${FULL_VERSION}_all.deb \
            --repo ${TARGET_REPO} \
            --clobber
